replicaCount: 3

release:
  environment: prod

resources:
  requests:
    cpu: 100m
    memory: 96Mi
  limits:
    cpu: 500m
    memory: 256Mi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: node-monitor
